services:
  go-app:
    container_name: go-app
    image: go-rest-api-optimized
    build: .
    ports: 
      - "8080:8080"
    depends_on:
      - "go-db"
  go-db:
    container_name: go-db
    image: postgres:16
    environment:
      POSTGRES_PASSWORD: asdf
      POSRGRES_USER: postgres
      POSTGRES_DB: postgres
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
volumes:
  pgdata: {}

